default:
  @just --list

apply:
  #!/usr/bin/env sh
  cd {{source_directory()}}/terraform
  tofu init
  tofu apply

destroy:
  #!/usr/bin/env sh
  cd {{source_directory()}}/terraform
  tofu  destroy

outputs:
  #!/usr/bin/env sh
  cd {{source_directory()}}/terraform
  tofu output

ssh node:
  #!/usr/bin/env sh
  pushd {{source_directory()}}/terraform > /dev/null
  IPV4=$(tofu output -json | jq -r '.ipv4[{{node}}]')
  popd > /dev/null
  ssh root@${IPV4}

configure node:
  #!/usr/bin/env sh
  set -eou pipefail

  pushd {{source_directory()}}/terraform > /dev/null
  IPV4=$(tofu output -json | jq -r '.ipv4[{{node}}]')
  popd > /dev/null

  echo "= Provisioning id.tjo.space"
  cat install.sh | ssh root@${IPV4} 'sudo bash -s'
