- name: Create code group
  ansible.builtin.group:
    name: code
    gid: 1010
    system: true
    state: present

- name: Create code user
  ansible.builtin.user:
    name: "code"
    uid: 1010
    group: code
    system: true
    home: /var/lib/code
    state: present

- name: Prepare directories
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    mode: "0750"
    owner: "code"
    group: "code"
  loop:
    - "/srv/data/forgejo"
    - "/srv/data/valkey"
    - "/etc/forgejo/templates/custom"
    - "/etc/anubis"
  tags: config-reload

- name: Copy service configuration
  ansible.builtin.template:
    src: root{{ item }}
    dest: '{{ item }}'
    mode: '0600'
    owner: "1010"
    group: "1010"
  loop:
    - "/etc/forgejo/app.ini"
    - "/etc/forgejo/templates/custom/footer.tmpl"
    - "/etc/anubis/botPolicies.yaml"
  tags: config-reload

- name: Copy network configuration
  ansible.builtin.template:
    src: 'root/etc/containers/systemd/{{ item }}'
    dest: '/etc/containers/systemd/{{ item }}'
    mode: '0600'
    owner: root
    group: root
  loop:
    - code.network
  tags: config-reload

- name: Copy container configuration
  ansible.builtin.template:
    src: 'root/etc/containers/systemd/{{ item }}.container'
    dest: '/etc/containers/systemd/{{ item }}.container'
    mode: '0600'
    owner: root
    group: root
  loop:
    - valkey
    - valkey-exporter
    - forgejo
    - anubis
  tags: config-reload
  register: container_configs

- name: systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  tags: config-reload

- name: Start containers
  ansible.builtin.systemd:
    name: "{{ item }}"
    # In case container config changed, restart it. Otherwise we only make sure it's running.
    state: "{{ container_configs.results | selectattr('item', 'equalto', item) | map(attribute='changed') | list | first | ternary('restarted', 'started') }}"
    enabled: true
  loop:
    - valkey
    - valkey-exporter
    - forgejo
    - anubis
  tags: config-reload
